### ISSUE TITLE
Audio stream restarts at 415 in 360° Player on iPhone

### ISSUE THREAD

**Issue by Llewellynvdm** [scottschiller/SoundManager2#130] opened 2016-04-18 08:11 UTC
Hi, I have added this player to a [Joomla Component](https://github.com/SermonDistributor/Joomla-3-Component) and it works great!

Today I was informed that it only plays audio until 415 and then restarts on an iPhone, I tested it and found that this is unfortunately correct..

I have look at the implementation in the [view](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/views/sermon/tmpl/default.php#L58) and in the [layout](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/layouts/audioplayer.php#L33) to insure the error is not due to wrong implementation.

But accordion to your [documentation](http://www.schillmania.com/projects/soundmanager2/demo/360-player/) it seems correct.

Here is a link to a [website where the component](http://www.loudvoice.org/a/sermon/god-is-inescapable) is being used. Just you know, it works on desktop perfectly... it is only on iPhone.

Any ideas what may cause this kind of behavior?

**Comment by scottschiller** [comment] 2016-04-21 14:05
Pardon late follow-up, here -

This sounds like the same issue someone else reported recently - is it possible your server is serving up MP3s, etc., with gzip, which now causes problems on newer iOS?

SM2 should not be the issue, it uses native HTML5 players under the hood and doesn't have any control over decoding etc. Unless they use Flash for playback, other players will have the same issue.

Take a look at this one for details - it sounds related.
https://github.com/scottschiller/SoundManager2/issues/128

Also:
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#serving-audio

**Comment by Llewellynvdm** [comment] 2016-04-22 11:49
Okay I will try turning gzip off, but this is not nice.... I mean gzip helps with speeding up your website. To turn it off is not ideal. But I will first test this and get back to you thanks!

**Comment by scottschiller** [comment] 2016-04-23 02:40
@Llewellynvdm: gzip speeds up your site, _but_, to apply it to binary assets is wrong. All good, and can be fixed, but you want to apply gzip selective. On the web, gzip is only useful when applied to text-based formats like HTML, CSS, JS, SVG and so on. Don't apply it to binary stuff - images, .zip, .mp3, and so on, or you will inevitably end up triggering bugs like this.

gzip also means the server has to spend time compressing the asset before sending, and in the case of larger binary assets, it may mean more CPU on the server. While not prominent, it is mentioned toward the bottom of my "serving audio" note, there.

**Comment by Llewellynvdm** [comment] 2016-04-24 17:50
@scottschiller We are using Joomla's php framework and our application is a component that runs in Joomla as an add-on. The gzip is a global switch in Joomla and not controlled on the component level. 

So I turned the gzip feature OFF on the global scale and found that it still restarts the audio at 415 seconds.  So this has not solved the issues, and so from this I think it is not related to the gzip in this case.

**Comment by scottschiller** [comment] 2016-04-25 02:03
@Llewellynvdm Hmm, thanks for the note.

Something to try, presuming you have OS X and Safari... try loading, or dragging and dropping that MP3 _right into Safari itself_, and see how it plays. That will eliminate Joomla, network and SM2 altogether and will leave just the browser + OS' built-in decoder to test. If playback fails there, it's probably some issue with the way that file was encoded.

If playback works OK locally, then it's either SM2 or something with your network and/or the way you're serving files, and it's _probably_ the network.

Make sure you have HTTP partials / byte ranges enabled, among other things. HTML5 clients request pieces of files, not the entire thing in a single request.

More on how HTML5 clients download audio, here:
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#client-requests

**Comment by scottschiller** [comment] 2016-04-25 02:31
@Llewellynvdm: Found a wrinkle. 😉 

Looking at the file itself from the link in your first message, it appears to be a very low bitrate - perhaps uncommon in the wild, and something to consider. Your MP3 is encoded as Mono, 16,000 hz, 24 kb/sec bitrate. Most MP3s (at "CD quality") are 44,100 hz, 128 kb/sec or greater.

I have a feeling this low-bitrate encoding is the reason for the strange behaviour on iOS.

It's notable that I have heard a few parts of the file repeated while playing, i.e., "drains and dry" was said twice. It's as though the MP3 itself is just badly-encoded.

Playing the file directly from within Safari on my iPhone 6 (loading the MP3 URL directly) and from the file system on desktop OS X Safari, it's notable that the UI says "Live Broadcast", and the usual time-seeking controls are not shown. That is interesting, and presumably related to the way this particular file has been encoded.

When loading your site and playing the file from Safari, I notice that the 360 UI does not show progress of time - however, that is to be expected because of the "live broadcast" factor mentioned earlier, time-seeking controls were not presented and thus time / seeking are not options on iOS for this particular file.

I did get the sermon re-starting as you mentioned, both when loading from the website and locally in my own tests (using my own server, not Joomla etc.), around "every one of us ... must give ... an account of himself."

My recommendation is to re-encode this MP3 from the original higher-quality source, and use a higher bitrate - at least 32,000 bits/second, to start - and see if that helps things. If that doesn't work, try 64 kbps and then 128 kbps. It may be that encoding in mono vs. stereo is a cause, so try encoding in stereo.

**Comment by Llewellynvdm** [comment] 2016-05-02 16:38
@scottschiller I am wondering take a look at these few lines, it is the [download method in php](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/controllers/download.php#L83) do you think I can change anything here to solve the issue? I am setting the transfer-encoding to Binary.

Any ideas? since I don't think it is the quality, the files work in other players. You see these files has been on-line and in use for many years. It did work in previous players like jwplayer.

**Comment by Llewellynvdm** [comment] 2016-05-02 16:41
Also note that all the links that are used on the site has a session timer added to it, it will only work for the length of the session. The sessions is usually around 15minuts. I have tested your player in all browsers I know and it works. It is just when opening the player in an IOS device that it breaks.

**Comment by scottschiller** [comment] 2016-05-07 15:19
To be clear, I think this is an issue with the encoding of the file and the way it's handled on newer iOS devices (and possibly, desktop Safari.) jwplayer likely would have worked in the past because it uses Flash for playback - however, that won't work on iOS which doesn't support Flash, and only uses HTML5 - so you'd be back to square one.

**Comment by Llewellynvdm** [comment] 2016-05-10 19:17
Sorry, I am not trying to be unkind, but it is not the encoding, we are talking about 4000+ audio files (many different encoding, some with 128 kbps) that has been used on-line for over 8 years on multiply websites and all kind of players, we have this same audio files in html5 only players and they work. 

Yet your player does not play them on IOS devises, I am not that advanced in JavaScript else I would have tried to debug it myself.

**Comment by scottschiller** [comment] 2016-07-16 17:33
Curious to hear if you got this one sorted; I have a feeling it's an issue between your old audio files and a change in iOS' built-in HTML5 playback support - but, happy to hear if you found the cause.

**Comment by Llewellynvdm** [comment] 2016-07-16 17:41
Hi I did find the issue, please read here https://github.com/SermonDistributor/Joomla-3-Component/issues/17#issuecomment-230113435 so it was not your player, and I have kept your player in the component.

It seems like this [PHP that pass](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/controllers/download.php#L70) the file one to the player is not doing it correctly.

Do you have any advice surrounding that bit of PHP script that builds the headers. I have to fix the issue that is for sure :+1:

**Comment by Llewellynvdm** [comment] 2016-07-16 17:52
Could this be the issue?
~~~
header("Content-Transfer-Encoding: Binary");
~~~
since I remember you spoke about not encrypting the file again.... yet I thought this just tells the browser that it is a Binary file... since all audio are.

**Comment by scottschiller** [comment] 2016-07-16 18:02
Ah-ha. Yeah, often it's either encoding of the MP3, _or_, something about how the file is served that trips up folks.

My recommendation: Look at a vanilla Apache HTTP response for the same MP3 file - no PHP skulduggery 💀 😆 - and see what headers it provides.

Generally, you _do_ want headers like `content-type` and `content-length`, and you _don't_ want gzip or other redundant encoding applied to binaries. Transfer-encoding doesn't seem suspect, but I say try dropping headers that seem extraneous relative to a vanilla Apache response and see what happens.

**Comment by Llewellynvdm** [comment] 2016-07-16 18:22
That is what I am doing in [this function](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/controllers/download.php#L107)

You see the file can come from the local server, or an url. If I want to control the download this seems like the only way to handle the file... instead of the direct link that leaves you out of the loop really.

How well do you know PHP, is there a way to use the same headers without using the same domain?

I would really like to stream the file instead of these gymnastics.... but I need to use the URL of where the component runs and not from-where the file comes, to insure that I can hide the file from users that don't have right to access the file... since the system updates the whole link every few minutes. Lots of benefits in hiding the real file location to be honest.

**Comment by scottschiller** [comment] 2016-07-16 18:39
Sounds like the PHP is the cause of headaches - either headers, or something else corrupting the response somehow.

My $.02: Compare response headers from Dropbox, etc., for the original file asset - assuming it works if you were load it from iOS there, vs. what you're serving via PHP, and drop whatever headers seem extraneous.

**Comment by Llewellynvdm** [comment] 2016-07-17 17:31
This looks like the answer to our problem:
https://mobiforge.com/design-development/content-delivery-mobile-devices

**Comment by scottschiller** [comment] 2016-09-18 18:07
Closing as this is ultimately an encoding and/or HTTP transfer issue - not an SM2 issue. Interesting story and investigation into the cause, however. This is a very particular behaviour I've never had reported before.

**Closed by scottschiller** 2016-09-18 18:07 UTC
