### ISSUE TITLE
Beginning playback from position irregularities

### ISSUE THREAD

**Issue by georgeholt** [scottschiller/SoundManager2#88] opened 2015-07-22 09:22 UTC
I'm in the process of building a player for the company I work for and one of the features I need to implement is a quality switching mechanism. When a user switches quality profiles it needs to:

a) Automatically begin playback of the new profile if the old profile was busy playing
b) Resume playback from last position of the previous profile

According to the documentation, using the `from` option when calling `soundManager.createSound` should begin playback from the position specified, however I'm not seeing this in all cases.

Both `webm` and `m4a` behave as intended from what testing I've done, however both `mp3` and `oga` don't, instead they:
- Begin playback from the beginning of the file, but
- their timer starts from the position I've asked it to start from

For example:

``` js
soundManager.createSound({
    autoPlay: true,
    url: "http://example.com/path/to/media.mp3",
    from: 5000, // begin playback from the 5s position
    whileplaying: function() {
        $('#some-element-id').html(this.position);
    }
});
```

This will begin playback of the `http://example.com/path/to/media.mp` file from the **start** of the file, but the `#some-element-id` will start with it's initial value set to `5000`.

**Comment by jakalofnaar** [comment] 2015-07-22 09:42
Here is an example using JSBin: http://jsbin.com/rimita/edit?html,js,output

Note I had to use the `position` option to get it to resume from the desired position, `from` wasn't doing anything, but the issues in my OP still persist.

**Comment by scottschiller** [comment] 2015-07-26 01:04
Thanks for the report, pardon the late follow-up here.

It may be the use of `from` within `createSound()` here that is the cause of the problem. Sorry this isn't more clear in documentation, but there is a special case around playing a sound with position parameters before it has loaded.

SM2 _should_ do the right thing and begin playback from the right position in a file regardless of type etc., but there are differences between the way Flash and HTML5 request and allow seeking within files.

HTML5 will try to negotiate byte ranges (HTTP partials) by default, and thus once the `onload()` event has fired for a sound you should be able to seek to arbitrary positions within the sound.

With Flash, you must wait for `onload()` to fire before you can seek as well.

An important distinction: Under HTML5, the onload event can fire very early - it's actually when the sound has fired the HTML5 "canplay" event. Because Flash 8/9 use a single HTTP request to load sound, they do not use byte ranges and thus you can only seek as far as a sound has loaded. Thus, SM2 takes the conservative route and waits for the sound's load event to fire before you can seek.

SM2 tries to normalize all of this within the API, such that if you create a sound object and then call `play({ position: 5000 });` for example, it will first load and wait for `onload()` before firing `setPosition()` and beginning playback.

Put another way, you could do this and have the same effect:
```someSound.load({
  onload: function() {
    this.play({
      position: 5000
    });
  });
});```

**Comment by jakalofnaar** [comment] 2015-07-31 10:14
Sorry for the late reply, and many thanks for the response.
I tried using `play({ position : 5000 });` without success, but the `onload() => this.play({ position : 5000 });` method works.

**Comment by scottschiller** [comment] 2017-06-04 17:27
Closing this one out; closing thoughts! 😉 It's possible some HTML5 clients might have issues seeking "right away" given the way `createSound()` works - IIRC internally I have SM2 wait for `onload()` before attempting to set position, but there's no harm in explicitly waiting for that event yourself to be safe.

FWIW, V2.97a.20170601 was just released and is largely a maintenance update.

**Closed by scottschiller** 2017-06-04 17:27 UTC
