### ISSUE TITLE
Uncaught TypeError: h._pause is not a function

### ISSUE THREAD

**Issue by taykcrane** [scottschiller/SoundManager2#77] opened 2015-06-17 01:00 UTC
Hi,

Working on a project and I've encountered a bug that I cannot find the source of. I've only been able to reproduce it on a single machine, OSX Yosemite running Chrome 43. When I try to pause the sound, I receive:
"Uncaught TypeError: h._pause is not a function"
This error is thrown on "soundmanager2.js:37".

Is this something you've seen before? Can you help me debug?

**Comment by scottschiller** [comment] 2015-06-24 03:19
Howdy,

Pardon late reply, vacation etc. :smile: 

Is there any chance you can reproduce this on the current SM2 homepage or related demos? Based on the error, it looks like you have a minified version of the SM2 script running. From the unminified source, `_pause` is a method called on the Flash movie - so it's possible something is killing the Flash movie or otherwise nulling it out. It's possible that Chrome's newer power-saving plugin-disabling / snoozing features are affecting the JS/Flash bridge, so it's worth considering that angle as well.

The next point: If `._pause` is being called, SM2 is almost certainly running in JS + Flash-mode, which is interesting. By default, SM2 prefers 100% HTML5 mode if available and nearly all modern browsers support playing the default "required" audio format (MP3) without needing Flash - so that is also worth looking into. If your machine is running Chrome or Firefox on Ubuntu, for example, and the OS doesn't have the "non-free" MP3 codec support package installed at the OS level, that may be why it's falling back to using Flash to get MP3 support.

_Finally_ - if you don't need MP3 support, you can disable that in SM2. Let me know the particulars of your set-up, and I can help troubleshoot further.

**Comment by scottschiller** [comment] 2017-06-04 17:32
V2.97a.20170601 is out; if you can still repro this, do let me know! Meanwhile, closing this one out before its second birthday comes around. 😉

**Closed by scottschiller** 2017-06-04 17:32 UTC
